#!/bin/bash

script_name=${0##*/}
script_full=`realpath $0`				#/path_to/build

value=0
dockerhub="labsonar/"

if [ "$#" -ge 3 ]; then
	port=$3
else
	port=8888
fi

image=""
case "$1" in
	processing)
		docker build --build-arg MY_USER=$USER --build-arg MY_UID=$(id -u) --build-arg MY_GID=$(id -g) -f processing_dockerfile -t "$dockerhub"processing .
		image="processing"
	;;

	root_processing)
		docker build -f processing_dockerfile -t "$dockerhub"root_processing .
		image="root_processing"
	;;

	pytorch)
		docker build --build-arg MY_USER=$USER --build-arg MY_UID=$(id -u) --build-arg MY_GID=$(id -g) -f processing_dockerfile -t "$dockerhub"processing .
		docker build --build-arg MY_USER=$USER --build-arg MY_UID=$(id -u) --build-arg MY_GID=$(id -g) -f pytorch_dockerfile -t "$dockerhub"pytorch .
		image="pytorch"
	;;

	root_pytorch)
		docker build -f processing_dockerfile -t "$dockerhub"root_processing .
		docker build -f pytorch_dockerfile -t "$dockerhub"root_pytorch .
		image="root_pytorch"
	;;

	synthesis)
		docker build --build-arg MY_USER=$USER --build-arg MY_UID=$(id -u) --build-arg MY_GID=$(id -g) -f processing_dockerfile -t "$dockerhub"processing .
		docker build --build-arg MY_USER=$USER --build-arg MY_UID=$(id -u) --build-arg MY_GID=$(id -g) -f pytorch_dockerfile -t "$dockerhub"pytorch .
		docker build --build-arg MY_USER=$USER --build-arg MY_UID=$(id -u) --build-arg MY_GID=$(id -g) -f synthesis_dockerfile -t "$dockerhub"synthesis .
		image="synthesis"
	;;

	root_synthesis)
		docker build -f processing_dockerfile -t "$dockerhub"root_processing .
		docker build -f pytorch_dockerfile -t "$dockerhub"root_pytorch .
		docker build -f synthesis_dockerfile -t "$dockerhub"root_synthesis .
		image="root_synthesis"
	;;

	sonar)
		docker build --build-arg MY_USER=$USER --build-arg MY_UID=$(id -u) --build-arg MY_GID=$(id -g) -f processing_dockerfile -t "$dockerhub"processing .
		docker build --build-arg MY_USER=$USER --build-arg MY_UID=$(id -u) --build-arg MY_GID=$(id -g) -f pytorch_dockerfile -t "$dockerhub"pytorch .
		docker build --build-arg MY_USER=$USER --build-arg MY_UID=$(id -u) --build-arg MY_GID=$(id -g) -f synthesis_dockerfile -t "$dockerhub"synthesis .
		docker build --build-arg MY_USER=$USER --build-arg MY_UID=$(id -u) --build-arg MY_GID=$(id -g) -f sonar_dockerfile -t "$dockerhub"sonar .
		image="sonar"
	;;

	root_sonar)
		docker build -f processing_dockerfile -t "$dockerhub"root_processing .
		docker build -f pytorch_dockerfile -t "$dockerhub"root_pytorch .
		docker build -f synthesis_dockerfile -t "$dockerhub"root_synthesis .
		docker build -f sonar_dockerfile -t "$dockerhub"root_sonar .
		image="root_sonar"
	;;

	all)
		$script_full processing 8886
		$script_full pytorch 8887
		$script_full synthesis 8888
		$script_full sonar 8500-9000

		$script_full root_processing 8886
		$script_full root_pytorch 8887
		$script_full root_synthesis 8888
		$script_full root_sonar 8500-9000
	;;

	*)
		echo "$script_name [root_]{processing | pytorch | synthesis | sonar | all}"
		exit 1
	;;
esac


docker create -it --gpus all -v $HOME:$HOME -p "$port":"$port" "$dockerhub""$image"

exit 0