#!/bin/bash

script_name=${0##*/}
script_full=`realpath $0`				#/path/build.sh

value=0
dockerhub="labsonar/"

if [ "$#" -ge 3 ]; then
	port=$3
else
	port=8888
fi

image=""
case "$1" in
	processing)
		docker build -f processing_dockerfile -t "$dockerhub"processing .
		image="processing"
	;;

	pytorch)
		docker build -f processing_dockerfile -t "$dockerhub"processing .
		docker build -f pytorch_dockerfile -t "$dockerhub"pytorch .
		image="pytorch"
	;;

	synthesis)
		docker build -f processing_dockerfile -t "$dockerhub"processing .
		docker build -f pytorch_dockerfile -t "$dockerhub"pytorch .
		docker build -f synthesis_dockerfile -t "$dockerhub"synthesis .
		image="synthesis"
	;;

	all)
		if [ "$#" -ge 2 ]; then
			$script_full processing $2 8886
			$script_full pytorch $2 8887
			$script_full synthesis $2 8888
		else
			$script_full processing 8886
			$script_full pytorch 8887
			$script_full synthesis 8888
		fi
	;;

	*)
		echo "$script_name {processing | pytorch | synthesis | all}"
		exit 1
	;;
esac 


if [ "$#" -ge 2 ]; then
	docker create -it --gpus all -v "$2" -p "$port":"$port" "$dockerhub""$image"
else
	docker create -it --gpus all -p "$port":"$port" "$dockerhub""$image"
fi


exit 0